# Site settings
title: "Tyler Bernard"
description: "a website all about me"
baseurl: "" # Leave blank for the main site; use "/subdirectory" for a subdirectory
url: "https://tgbernard19.github.io" # Your site's URL

# Author information
author: 
  name: "Tyler Bernard"
  email: "tgbernard19@berkeley.eddu"

# Build settings
markdown: kramdown # This is Jekyll's default Markdown parser
theme: jekyll-theme-cayman # Replace 'minima' with any other Jekyll theme you prefer

# Folder settings
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
